### ISSUE TITLE
Duplication of copied entry(Test case) at destination.

### ISSUE THREAD

**Issue by cpz9f** [guapo832/esiSwaggerServer#11]
Please go to the home page and try drag and drop on any test case. 
- Lets consider this, we are trying to copy "Test Name6" from "/Scope1/Subscope2" to "Scope1".
- Select the copy option on the window appears after you drag the Test case to destination.
- Now go to the Tree view.
-Now expand the destination scope or subscope.
-You will see two copies of the dragged test cases.
-Now expand the source scope or subscope.
-You see the copied test case missing there.

Expected : 
- We should not see the duplicate copies of the dragged file.
-Also we should not see the particular test case missing at the destination.

![image](https://cloud.githubusercontent.com/assets/22528167/21037794/281545aa-bd96-11e6-9dbd-9846cca6619b.png)

**Comment by guapo832** [comment]
Thanks I'll take a look at these tonight

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by guapo832** [comment]
will look into this today

**Comment by guapo832** [comment]
I believe I have fixed this bug.
