### ISSUE TITLE
Drag and drop 2

### ISSUE THREAD

**Issue by cpz9f** [guapo832/esiSwaggerServer#12]
After performing the bug no. 1 scenario, once try refreshing the page. Now, we don't see the copied file in the destination Scope or Subscope both at tree and modal views. But when we try to copy the same Test case from the a source to the same destination. We wont be able to copy. Which isn't expected. When we don't see the entry in a Scope, we should be able to copy that scope from a source scope to that destination.

In below screen shot, please check that there is no "Test Name2" in the Scope1(Tree and Modal view)

Expected : 
1. Either we should be able to copy the same Test case from source to destination.
    or
2. We should see the same test case in both Tree and Modal views.

![image](https://cloud.githubusercontent.com/assets/22528167/21038518/1d26a0e8-bd9c-11e6-9a26-e8220a2dfd0d.png)

**Comment by guapo832** [comment]
will look into this tonight

**Comment by guapo832** [comment]
I believe I have resolved this issue.
